### ISSUE TITLE
Required packages being masked in Gentoo repos: dev-java/gin in particular

### ISSUE THREAD

**Issue by WPettersson** [jgenco/jgenco-overlay#23]
From Gentoo repositories

```
# Volkmar W. Pogatzki <gentoo@pogatzki.net> (2024-04-08)
# Java libraries without consumers.
# Removal on 2024-05-08, bugs #853100 #716228.

- dev-java/gwt-2.9.0-r3::gentoo (masked by: package.mask)
- dev-java/gin-2.1.2-r1::gentoo (masked by: package.mask)
For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
```

sci-mathematics/rstudio depends directly on dev-java/gin:2.1, and dev-java/gin:2.1 depends on dev-java/gwt:2.8. Removal of these on the 2024-05-08 will break rstudio unless we bring them in from elsewhere.

I don't know if the best option is to bring those packages into this repository, but if it is, I can probably make some pull requests to do so.

**Comment by jgenco** [comment]
I'm aware of the packages being removed from `::gentoo`.  I have a local branch that includes the `dev-java/gin` and `dev-java/gwt` and a newer rstudio-2024.04.0.696. I was planning to push it this weekend, but I ran into a problem with the QT5 version of rstudio(QT6 untested).  My belief is `dev-qt/qtwebengine-5.15.13_p20240322`  is the problem and _not_ RStudio.

RStudio loads fine and then the windows just goes grey.  I can alt-tab to another window during loading and delay the grey, but after a couple clicks or typing a few characters it just goes grey. 
In the RStudio log it just says:
`ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() src/cpp/session/SessionMain.cpp:1508`
I notice this with the current rstudio-2024.04.0.662 as well.

Using qtwebengine example browsers and `www-client/qutebrowser` produce `Renderer process crashed (status 5)`.
My theory is qtwebengine crashes rstudio detects this and runs `detectParentTermination()`.  This could be my old GPU(Sandy Bridge) or something else.  So I held off pushing because I couldn't actually test the QT5 version.

**Comment by WPettersson** [comment]
If you're already working on it, I'll leave you be :) I just wanted to help out if you hadn't started working on it yet.

I can try to test the new version of rstudio though, see if I see the same thing

**Comment by jgenco** [comment]
If you want. I notice the problem even in `main` - rstudio([~amd64] 2024.04.0.662) and qtwebengine:5 (5.15.13_p20240322). You _might_ have to recompile `rstudio` after installing `qtwebengine`.
My normal USE flags are `panmirror qt5 quarto server -clang -debug -doc -electron -qt6 -test`

I think I'll push next weekend and see what happens as there are at least a half dozen people that use rstudio(~amd64) and 2024.04.0.xxx is about to be released.

**Comment by jgenco** [comment]
I have pushed three commits - an updated rstudio(839a6cf) and added gwt(c2900f4) and gin(77d39fc).  The good news rstudio works fine with qtwebengine-6.7.0 works.

I'll leave this open over the weekend to catch any problems.
