### ISSUE TITLE
net-libs/deno-1.41.0 and rust-1.77.1

### ISSUE THREAD

**Issue by fvalenduc** [jgenco/jgenco-overlay#24]
I wondered why the current stable version (1.77.1) was not allowed to compile the latest version in the overlay (1.41.0). So I copied the ebuild and updated the rust version. It compile perfectly fines. 
It would be good to always allow the current stable version of rust available in gentoo, which is nowadays needed to compile chromium.

**Comment by jgenco** [comment]
The reason I have `deno` set to a range of rust versions is because I had a previous problem where `deno` only compiled _and_ worked with one version of rust. Perhaps that was a one time thing.

Did you install deno compiled with `rust-1.77.1`? If so can you re-emerge `app-text/quarto-cli` and make sure quarto-cli bundles correctly as this was a hangup that time.
Also, can you run `USE="test" ebuild deno-1.41.0.ebuild test` this will build and test deno.

Looking at my logs 2 test fail.
```
failures:
    repl::pty_complete_imports_no_panic_empty_specifier
    watcher::fmt_watch_without_args_test

test result: FAILED. 1495 passed; 2 failed; 20 ignored; 0 measured; 0 filtered out; finished in 2919.05s
```
It is my belief they fail because of Gentoo's sandbox but I have not investigated further.

**Comment by fvalenduc** [comment]
I managed to compile deno with rust-1.77.1. Afterwards, I compiled quarto-cli and rstudio with quarto support. All that went without problem.
